### ISSUE TITLE
Sonify distance to target

### ISSUE THREAD

**Issue by Paulpanther** [Paulpanther/AudioMaze#6]
- How many sound sources?

**Comment by ShirleyNekoDev** [comment]
Check out the following properties on AudioSource:
- spatialize
- spatialBlend
- spread (vs panStereo)

**Comment by Paulpanther** [comment]
There is none :( Will add pathfinder to build it ourselfs

**Comment by Paulpanther** [comment]
Depends on #7

**Comment by Paulpanther** [comment]
Global Audio Collider
